on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  disk_space:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Free Disk Space Before Build
        run: |
          echo "Disk space before cleanup:"
          df -h
          echo "Disk space after cleanup:"
          df -h
  test:
    runs-on: ubuntu-latest
    env:
      HF_HOME: ./cache/transformers
      FLAIR_CACHE_ROOT: ./cache/flair
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Torch cpu
        run: pip install torch --index-url https://download.pytorch.org/whl/cpu
      - name: Install Flair dependencies
        run: pip install -e .[word-embeddings]
      - name: Install unittest dependencies
        run: pip install -r requirements-dev.txt
      - name: Show installed dependencies
        run: pip freeze
      - name: Cache downloaded models/datasets
        uses: actions/cache@v3
        with:
          path: ./cache
          key: cache-v1.2
      - name: Check Diskspace before tests
        run: |
          echo "Disk space before tests:"
          df -h
      - name: Run tests
        run: |
          python -c 'import flair'
          pytest --runintegration -vv
      - name: Check Diskspace after tests
        run: |
          echo "Disk space after tests:"
          df -h