name: Debug Disk Space

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Free Disk Space Before Build
      run: |
        echo "Disk space before cleanup:"
        df -h
        echo "Disk space after cleanup:"
        df -h
